formio/core

src/base/component/Component.spec.ts, src/base/component/Component.ts
Ticket: https://formio.atlassian.net/browse/FIO-6123
=> FIO-6123-Added an array cleanup to the removeAttachedListeners method and wrote test for it

src/types/Access.ts, src/types/Action.ts, src/types/Form.ts, src/types/Role.ts, src/types/Submission.ts, src/types/index.ts, src/types/package.json, src/types/project/Project.ts, src/types/project/index.ts, src/types/project/settings/ProjectSettings.ts, src/types/project/settings/authorization/index.ts, src/types/project/settings/authorization/ldap.ts, src/types/project/settings/authorization/oauth.ts, src/types/project/settings/authorization/saml.ts, src/types/project/settings/index.ts, src/types/project/settings/integrations/dataConnections.ts, src/types/project/settings/integrations/eSign.ts, src/types/project/settings/integrations/email.ts, src/types/project/settings/integrations/fileStorage.ts, src/types/project/settings/integrations/index.ts, src/types/project/settings/integrations/reCaptcha.ts
Needs review on optional/required properties. Also there might be missing ones
=> types for core entities added

src/process/normalize/index.ts
https://formio.atlassian.net/browse/FIO-7958
Fixed a typo in the port of the `normalize` processor fn from formio.js to core.
n/a
n/a
OSS tests pass now!
=> FIO-7958: fix typo in normalize processor fn

.github/workflows/repo.yml
https://formio.atlassian.net/browse/FIO-7146
Runs tests and checks app build process
Default configuration
n/a
n/a
Checked tests locally then ran in pipeline to validate same tests ran.
=> FIO-7146: gh actions for repository

src/process/validation/i18n/en.ts
https://formio.atlassian.net/browse/FIO-8106
Add translation for invalid date validation error.
n/a
n/a
n/a
=> FIO-8106: add invalidDate error translation

src/process/normalize/index.ts
https://formio.atlassian.net/browse/FIO-8106
Tags should normalize to string value by default.
n/a
n/a
n/a
=> FIO-8106: add default storeas value to tags

src/process/validation/rules/validateCustom.ts, src/process/validation/rules/validateJson.ts, src/process/validation/util.ts
https://formio.atlassian.net/browse/FIO-8121
changed JSON response of jsonLogic and custom validation error
no
no
manually
=> Fix json and custom validation errors response

src/process/filter/index.ts
Fix OSS tests for https://github.com/formio/core/pull/79
=> FIO-8218: Fix tests for PR 79

src/process/__tests__/process.test.ts
https://formio.atlassian.net/browse/FIO-8218
Add tests for FIO-8210
n/a
n/a
tests tested to test correctly
=> FIO-8218: add tests for FIO-8210

src/utils/index.ts
n/a
There is a problem with import paths, which causes @formio/js to throw an error.
n/a
n/a
n/a
=> fix path/import issue with JSONLogicEvaluator

src/process/validation/rules/__tests__/validateNumber.test.ts, src/process/validation/rules/validateNumber.ts
https://formio.atlassian.net/browse/FIO-8597
Added a condition that allows blank values for multiple number components.
Automated test added.
=> FIO-8597: fixed an issue with a blank value for a number component with multiple values enabled

package.json, yarn.lock
Updated coverage thresholds.  They went up!
=> udpated thresholds to current values

src/process/validation/rules/__tests__/validateNumber.test.ts, src/process/validation/rules/validateNumber.ts
https://formio.atlassian.net/browse/FIO-8597
Added condition to skip validation if value submitted for a number component with multiple values enabled is [].
n/a
Added test.
=> FIO-8597: fixed an issue with an empty array value for a number component with multiple values enabled

.vscode/launch.json, package.json, src/process/__tests__/fixtures/clearOnHideWithCustomCondition.json, src/process/__tests__/fixtures/clearOnHideWithHiddenParent.json, src/process/__tests__/fixtures/index.ts, src/process/__tests__/process.test.ts, src/process/clearHidden.ts, src/utils/formUtil.ts, src/utils/isParentHidden.ts
https://formio.atlassian.net/browse/FIO-8730
Previously, fields with 'Clear value when hidden' would be kept in submission object when the parent component is hidden. This PR brings a fix. 
*Use this section to justify your choices*
None
Manually + automated test added
=> FIO-8730: Fix submission has hidden fields when 'Clear value when hidden' is checked

src/utils/date.ts, src/utils/formUtil.ts
n/a
Since Day components `emptyValue` [was changed to an empty string](https://github.com/formio/formio.js/pull/5745), validation is broken. This PR changes the `isPartialDay` method to return `true` on an empty value.
Additionally, some type guards were changed to handle undefined components.
n/a
n/a
n/a
=> chore: fix formiojs tests

src/process/normalize/__tests__/normalize.test.ts, src/process/normalize/index.ts
https://formio.atlassian.net/browse/FIO-8798
Normalization for day component was updated according to changes in  
https://github.com/formio/core/pull/140
https://github.com/formio/core/pull/140
autotests
=> FIO-8798: update normalization for day component

Readme.md
https://formio.atlassian.net/browse/FIO-9028
Update the README to reflect this library's new purpose, data processing.
n/a
n/a
n/a
=> FIO-9028: update README

src/process/__tests__/fixtures/addressComponentWithOtherCondComponents2.json, src/process/__tests__/fixtures/index.ts, src/process/__tests__/process.test.ts, src/utils/formUtil.ts
https://formio.atlassian.net/browse/FIO-9085
Fixed empty Address value recognition when manual mode is enabled
None
Automated test added
=> FIO-9085: Fix address submission logic

src/process/__tests__/process.test.ts, src/process/hideChildren.ts
https://formio.atlassian.net/browse/FIO-9202
The issue is not reproducible in the master branch. The reason is that PR https://github.com/formio/core/pull/141 was not fully cherry-picked into 2.3.x. This PR adds missed logic from https://github.com/formio/core/pull/141 and a test.
Manually + test
=> 2.3.x - FIO-9202: fixed an issue where the data for the component inside fieldset insdie wizard is lost after submission

src/process/conditions/__tests__/conditions.test.ts
https://formio.atlassian.net/browse/FIO-9219
The problem was fixed by PR:
https://github.com/formio/core/pull/174
Current PR contains auto tests.
https://github.com/formio/core/pull/174
=> FIO-9219: condition is not equal to based on select box

src/process/__tests__/process.test.ts, src/process/validation/rules/validateDate.ts, src/process/validation/rules/validateUrl.ts
https://formio.atlassian.net/browse/FIO-9261
Skip url and datetime value validation when multiple value is enable and  the value is an empty array
manually + tests
=> FIO-9261: fixed an issue where empty multiple value for url and datetime causes validation errors

package.json, src/utils/formUtil/__tests__/eachComponentData.test.ts, src/utils/formUtil/eachComponentData.ts, src/utils/formUtil/eachComponentDataAsync.ts, yarn.lock
https://formio.atlassian.net/browse/FIO-9021
[PR #184](https://github.com/formio/core/pull/184): This PR broke the ability to iterate over nested form components in eachComponentData.
Unit testing
=> [2.3.x] FIO-9021: Fixed eachComponentData iteration for nested forms

package.json
https://formio.atlassian.net/browse/FIO-9507
Updated version to 2.4.0-dev.1
Better track recency of dev versions
n/a
n/a
n/a
=> CHORE - Update master version to 2.4.x

.gitignore
N/A
Added the .idea folder to the list of things that need to be ignored by git. Visual studio code will generate a .vscode folder for user and workspace settings. Webstorm generates a similar folder named .idea so I added it alongside .vscode in .gitignore
It annoying to see the .idea folder and subfolders when I type in ``git status`` each time
N/A
N/A
N/A
=> Added .idea to gitignore for webstorm users

src/process/normalize/__tests__/normalize.test.ts, src/process/normalize/index.ts
https://formio.atlassian.net/browse/FIO-8117
*Deleted survey from data if the value is set as falsy values, so that 9.x behaves similarly to 8.x*
*n/a*
*n/a*
*Automated test has been added. All tests pass locally*
=> FIO-8117 removed survey from data if value is falsy

src/process/__tests__/process.test.ts, src/process/process.ts, src/process/serverOverride/__tests__/serverOverride.test.ts, src/process/serverOverride/index.ts, src/types/BaseComponent.ts
https://formio.atlassian.net/browse/FIO-8409
Added serverOverride processor that overrides current component settings with the serverOverride object. Added tests.
https://github.com/formio/formio.js/pull/6019
manually + autotests
=> FIO-8409: added serverOverride processor and tests

src/process/conditions/__tests__/conditions.test.ts, src/utils/__tests__/formUtil.test.ts, src/utils/conditions.ts, src/utils/formUtil/index.ts, src/utils/index.ts
https://formio.atlassian.net/browse/FIO-9908
This is the PR https://github.com/formio/core/pull/232/files adopted for 2.3.x
=> 2.3.x: FIO-9908: fixed an issue where conditional setting with "show" set as a string does not work well

src/types/Component.ts
https://formio.atlassian.net/browse/FIO-10036
Added missed types
https://github.com/formio/formio/pull/1967
=> FIO-10036: added missing types
