src/sdk/Formio.ts
https://formio.atlassian.net/jira/software/c/projects/FIO/issues/FIO-6832
Fixed issue where submission used wrong  _fvid 
I investigated this issue and have chosen this solutions like most optimal because it does not affect other logic and everything works correctly.
PR in formio.js repo:
https://github.com/formio/formio.js/pull/5189
Tested Locally 
video: https://formio.atlassian.net/browse/FIO-6832?focusedCommentId=46246
=> FIO-6832: fixed issue where submission used wrong  _fvid 

src/sdk/Formio.ts
https://formio.atlassian.net/browse/FIO-6964
Previously, there was no check that `useSessionToken` method is executed on server side and as the function relates to `localStorage` and `sessionStorage` and they're not available in server environment, the app crashed.
None
Manually
=> FIO-6964: Fixes server crashing if useSessionToken option passed

src/utils/Evaluator.ts
Somehow the `templateSettings` private parameter got removed in #21 . This PR restores the templateSettings variable, although not as `private` because TS refused to compile it as such
=> revert accidental deletion of templateSettings

package.json, src/base/component/__tests__/Component.test.ts, src/components/__tests__/htmlcontainer.test.ts, src/components/input/__tests__/input.test.ts, src/process/validation/rules/__tests__/validateRemoteSelectValue.test.ts, src/process/validation/rules/validateRemoteSelectValue.ts, src/proxy/__tests__/Instance.test.ts, src/sdk/__tests__/Formio.test.ts
Core tests were failing because of (a) our JSDOM implementation and (b) some minor issues.
(a) JSDOM was instantiating a global `window` object, so any validation rules that are designed to only work on the server were returning `null` and not validating. Adding a simple environment variable that is only present when the test suite runs should mitigate this problem.
(b) `JSON.stringify()` will ignore values that do not correspond to JSON compatible values (i.e. object, array, number, string, boolean).
=> FIO-7462: fix failing tests

src/process/calculation/index.ts, src/process/conditions/index.ts, src/process/defaultValue/index.ts, src/process/fetch/index.ts, src/process/populate/index.ts, src/process/processReduce.ts, src/process/validation/validateProcess.ts, src/types/process/calculation/CalculationScope.ts, src/types/process/conditions/ConditionsScope.ts, src/types/process/defaultValue/DefaultValueScope.ts, src/types/process/fetch/FetchScope.ts, src/types/process/populate/PopulateScope.ts, src/types/process/validation/ValidationScope.ts
Updated:
- Processor scopes to contain affected components
- Removed components array from component when it's pushed to processors output
- Certain properties picked from validation error context
- `scope` default value added to processReduced, so it's not required to pass it
=> scopes updated and other little updates

src/sdk/Formio.ts
I found a pretty nasty bug with the ```getTempToken``` method where it would call the "current" endpoint with a double JWT token which makes the request fail with Bad Token.
The problem is the code @ https://github.com/formio/core/blob/master/src/sdk/Formio.ts#L1183 calls makeRequest with a new Headers object. A jwt-token is then added to that token @ https://github.com/formio/core/blob/master/src/sdk/Formio.ts#L1530.
This then completes the request, where a new jwt token is returned and calls setToken @ https://github.com/formio/core/blob/master/src/sdk/Formio.ts#L1610C16-L1610C24 and passes the opts that still contains the "header" option from the original request.
This sets the token and then calls "currentUser" @ https://github.com/formio/core/blob/master/src/sdk/Formio.ts#L1766 which …
=> Ensure we do not 'append' jwt tokens but set them.

src/process/validation/rules/__tests__/validateMultiple.test.ts, src/process/validation/rules/validateMultiple.ts
Previously, the "multiple" validation rule didn't account for certain premium components having an array data model. This PR accomplishes the easy fix: adding the component types to the multiple validation conditional that decides if that component needs to be validated as an array.
*However*, this raises a vital question: how do we infer a component’s data model from its JSON schema? Simply adding component types to a switch statement doesn't cover, for example, custom components.
=> FIO-7883: include premium components in 'multiple' validation conditional

src/process/process.ts, src/process/processOne.ts, src/types/BaseComponent.ts, src/utils/formUtil.ts
Fix incorrect `row` for nested forms when performing evaluations
=> fix calculation for nested forms

package.json, src/process/calculation/index.ts, src/process/conditions/index.ts, src/process/defaultValue/index.ts, src/process/filter/index.ts, src/process/index.ts, src/process/normalize/index.ts, src/process/process.ts, src/process/processOne.ts, src/process/validation/index.ts, src/process/validation/rules/__tests__/validateMultiple.test.ts, src/process/validation/rules/validateMultiple.ts, src/types/BaseComponent.ts, src/types/Component.ts, src/utils/formUtil.ts, src/utils/logic.ts
This PR makes a number of updates to fix server side validation in the Form.io Enterprise Server. Among other things, it
1. adds a "normalize" processor function to mimic the data normalization in the [renderer's updateValue](https://github.com/formio/formio.js/blob/15418d8ff0561f3ab42b7abd8ccd1556859245be/src/components/_classes/component/Component.js#L2700) method;
2. no longer mutates a separate `context.value` property, and instead uses a getter and a setter to derive from the `context.data` object; and
3. makes a number of other small changes to ensure compatibility with server side validation in the Enterprise Server.
=> FIO-7958: add normalize processor fn and derive context.value rather than mutate it directly

src/process/validation/i18n/en.ts, src/process/validation/rules/databaseRules.ts, src/process/validation/rules/validateCaptcha.ts
https://formio.atlassian.net/browse/FIO-7998
Adds captcha validation by modifying the `database` configuration parameter to include a call to a server-side `validateCaptcha` function
n/a
* [formio#1712](https://github.com/formio/formio/pull/1712)
n/a
=> FIO-7998: add validate captcha rule

package.json, src/experimental/base/array/ArrayComponent.ts, src/experimental/base/component/Component.ts, src/experimental/base/data/DataComponent.ts, src/experimental/base/index.ts, src/experimental/base/nested/NestedComponent.ts, src/experimental/components/datatable.ts, src/experimental/components/datavalue.ts, src/experimental/components/html.ts, src/experimental/components/htmlcontainer.ts, src/experimental/components/input/input.ts, src/experimental/components/test.ts, src/experimental/index.ts, src/process/processOne.ts, src/process/validation/__tests__/Validator.test.ts, src/process/validation/index.ts, src/process/validation/rules/asynchronousRules.ts, src/process/validation/rules/clientRules.ts, src/process/validation/rules/databaseRules.ts, src/process/validation/rules/evaluationRules.ts, src/process/validation/rules/index.ts, src/process/validation/validate.ts
https://formio.atlassian.net/browse/FIO-7958
Adds to #40 and:
1. adds an `asynchronousRules` set to cover cases like `validateRemoteSelectValue` that need access to fetch and therefore should not run in the sandbox evaluator;
2. commits minor fixes to test cases; and
3. follows normal naming convention with rule set variables.
n/a
n/a
OSS formio and formio-server tests pass with these changes.
=> FIO-7958: add asynchronous rule set

Changelog.md, package.json, src/process/__tests__/process.test.ts, src/process/filter/index.ts, src/process/validation/index.ts, src/types/BaseComponent.ts, src/utils/formUtil.ts
https://formio.atlassian.net/browse/FIO-7884
When calling eachComponentData, and when making a call within a nested form, we need to reset the "path" and child "data" object so that the child components "believe" that they are at the root level. The reason for this, is when you are building a nested form, you would never build that nested form with the knowledge that you would be embedding that form within a parent form. All of your logic and custom evals would be written as if the nested form context is at the root. Because of this, our eachComponentData method needs to "trick" the nested form to use the correct context when making evaluations.
None that I am aware of.
I wrote an automated test that would fail if the contexts were not what they are supposed to be.
=> FIO-7884: Fixed issues with processing data within nested form data structures.

package.json, src/utils/formUtil.ts, yarn.lock
https://formio.atlassian.net/browse/FIO-8040
Previously, `utils` object provided to evaluation context was using functions from formiojs. Now the functions are moved to core
Should preserve backwards compatibility
none
manually
=> FIO-8040: add functions from formiojs

src/process/calculation/__tests__/calculation.test.ts, src/process/calculation/index.ts, src/process/processOne.ts, src/utils/Evaluator.ts
https://formio.atlassian.net/browse/FIO-8049
* Since `value` is now a getter, we need to make it enumerable so that the Evaluator [correctly enumerates it]( into the arguments of the Function
* We also want to make sure that the component's value, if it exists, is passed in to the evaluation context
n/a
n/a
I added an automated test to describe behavior and the existing formio and formio-server tests are passing.
=> FIO 8049: fix value prop in evaluations

src/process/validation/rules/__tests__/validateCustom.test.ts, src/process/validation/rules/validateCustom.ts
https://formio.atlassian.net/browse/FIO-8055
When porting over validation logic, I included [preexisting logic that would not custom validate components with empty data unless they were required](https://github.com/formio/formio.js/pull/5398/files). This was later reverted as an error, and so needs to be included in core's validation logic.
n/a
n/a
I've added an automated test to record expected behavior. Additionally, all formio and formio-server tests pass with this change included.
=> FIO-8055: validate components that include custom validations, even when their data is empty

src/error/DereferenceError.ts, src/error/index.ts, src/process/dereference/index.ts, src/process/index.ts, src/process/process.ts, src/types/Component.ts
https://formio.atlassian.net/browse/FIO-8047
Because Data Table components have an array data model, the `filter` process will skip over their submission data with the expectation that their constituent components will be iterated over by `eachComponentData`. However, Data Table components that use the "Reference" data source populate their components at runtime, which means that the form component that the server has access to has only an empty array. This PR adds a "dereference" processor (similar to the existing field action that serves save-as-reference submission data) that dereferences a target resource's components and populates the component's `components` array with those component JSON definitions so that the server can correctly iterate over and validate them. 
This can and …
=> FIO-8047: add dereferencing processor for datatable comp

src/process/validation/rules/validateTime.ts, src/process/validation/util.ts, src/types/Component.ts, src/utils/__tests__/formUtil.test.ts, src/utils/date.ts, src/utils/formUtil.ts, src/utils/operators/DateGreaterThan.js
https://formio.atlassian.net/browse/FIO-8092
This PR more fully adopts component-specific `isEmpty()` logic from the formio.js renderer to FormUtils so that we can be sure things like [logical operators](https://github.com/formio/core/blob/ddba72c1cf085fd1ab2faa0850e4be9a05eadc68/src/utils/operators/IsEmptyValue.js#L22) work as expected. It also converts instance shim calls to `getValidationFormat` and `isPartialDay` for day components to preexisting utility functions in the core library.
n/a
n/a
Added automated tests around `isEmpty`.
=> FIO-8092: update isEmpty to isComponentDataEmpty and account for differing component data types

src/process/__tests__/process.test.ts, src/process/clearHidden.ts, src/process/conditions/__tests__/conditions.test.ts, src/process/conditions/index.ts, src/process/process.ts, src/types/BaseComponent.ts
https://formio.atlassian.net/browse/FIO-8100
The `conditionals` processor originally cleared submission data properties for components that were conditionally hidden. However, this fails to account for other ways a component might be hidden, such as Advanced Logic or custom logic within the component. This PR changes the `conditionals` processor to merely set `hidden` to true on the component and adds a `clearHidden` processor that is responsible for unsetting any submission data tied to hidden components.
n/a
n/a
Automated + manual
=> FIO-8100: add clearhidden processor to cover logic, conditions, and custom

src/process/validation/rules/__tests__/validateJson.test.ts, src/process/validation/rules/validateJson.ts
https://formio.atlassian.net/browse/FIO-8101
We need to evaluate custom JSON logic validations even if the value is falsy.
n/a
n/a
Added an automated test case
=> FIO-8101: always process json validation even if value is falsy

src/process/validation/rules/__tests__/fixtures/util.ts, src/process/validation/rules/__tests__/validateJson.test.ts, src/process/validation/rules/validateJson.ts
n/a
In fixing another blocker ticket, we came across the fact that JSONLogic validations were not receiving a full context object. This PR fixes that issue.
n/a
n/a
manually plus an automated test
=> Fix: JSONLogic validations should get same context as calculations

src/utils/__tests__/formUtil.test.ts, src/utils/formUtil.ts, src/utils/unwind.ts
https://formio.atlassian.net/browse/FIO-8143
Updates `eachComponent` family of functions to return a `[0]` path when iterating over array data components
Though this is a relatively small change, the impact of even small changes to `eachComponent` and `eachComponentData` can be enormous, because so much depends on them. I've written tests and existing tests pass, but special care should be taken whenever we change these particular functions.
n/a
Automated tests etc.
=> FIO-8143: update eachComponent to be able to return proper pathing

package.json
https://formio.atlassian.net/browse/FIO-8128
We've decided that the caller of `evaluateProcess` should be able to inject dependencies at the call site. This PR will allow libraries like `formio` and `formio-server` to easily read the contents of the minified core JS file into memory and inject that dependency into the vm's evaluation context.
n/a
n/a
n/a
=> FIO-8128: allow export of dist minified js

src/process/filter/__tests__/filter.test.ts, src/process/filter/index.ts
https://formio.atlassian.net/browse/FIO-8177
Filter processor was unsetting empty array values for dataGrid, editGrid, dataTable components. Now it preserves the values.
Backwards compatible with 8.5
no
unit tests added
=> Fio 8177 fix unsetting empty array values

src/process/filter/index.ts, src/process/validation/index.ts
https://formio.atlassian.net/browse/FIO-8210
Fix how filter post processor handles data object model type
no
no
manually
=> FIO-8210: fix nested form validation

src/process/validation/rules/__tests__/validateRequired.test.ts, src/process/validation/rules/validateRequired.ts
This reverts commit 672b0ed26e9285ad6e1de8971578bac66d147081, reversing changes made to 210207398d3b08eaa1b67472ee43ab0cd87771cd.
N/A
We need to revert this PR because it broke Checkbox "required" validations. If you have a required checkbox, it lets you not click it.
*Use this section to list any dependent changes/PRs in other Form.io modules*
*Use this section to describe how you tested your changes; if you haven't included automated tests, justify your reasoning*
=> Revert "Merge pull request #31 from ralfeis/master"

src/process/process.ts, src/utils/__tests__/formUtil.test.ts, src/utils/formUtil.ts
https://formio.atlassian.net/browse/FIO-8128
Adds an optional `includeAll` flag to `eachComponentData` and `eachComponentDataAsync` that will (on an opt-in basis) allow those two functions to iterate over components even when those components do not have an associated data object.
n/a
n/a
I wrote automated tests, and existing tests pass. Upstream, I tested versus tests in @formio/vm and formio-server@9.0.0 and everything is passing.
=> FIO-8128: adds includeAll flag to eachComponentData and eachComponentDataAsync

src/process/validation/__tests__/multiple.test.ts, src/process/validation/index.ts, src/process/validation/rules/__tests__/validateMultiple.test.ts, src/process/validation/rules/validateMultiple.ts
https://formio.atlassian.net/browse/FIO-8336
Skipping non-full value validation on multiple values components when they don't have any rows.
n/a
n/a
manually, tests added, all tests pass
=> FIO-8336 fix validation on multiple values

src/process/normalize/__tests__/normalize.test.ts, src/process/normalize/index.ts
https://formio.atlassian.net/browse/FIO-8037
Added number component normalization and corresponding tests.
n/a
n/a
Tested locally, existing tests pass in core and formio OSS. Added automated tests.
=> FIO-8037: added number component normalization

src/process/validation/rules/__tests__/validateAvailableItems.test.ts, src/process/validation/rules/validateAvailableItems.ts, src/types/Component.ts
https://formio.atlassian.net/browse/FIO-8254
*The DataSrc property is an optional property and is set to values by default. Therefore, by default, the dataSrc property is not specified for Select components with Data Source Type as values. A check for the possible Data Source Type as values was added. Now the  Select components with validation of only available values work as expected, including forms of earlier versions*
*n/a*
*n/a*
*Automated tests have been added. All tests pass locally*
=> FIO-8254 fixed available values validation error for Select component

src/process/normalize/index.ts, src/process/validation/rules/validateRequired.ts
n/a
The `validateRequired` rule needs to recursively evaluate objects (like select boxes), but it should not recursively evaluate nested data types (such as data grids, edit grids, etc.).
n/a
n/a
I've added automated tests. (coming soon...)
=> update validate required recursion to not recurse when nested data type

src/process/__tests__/process.test.ts
https://formio.atlassian.net/browse/FIO-7675
Remove key from core. Believe @formio/core and @formio/js were running in parallel when the change to formio.js was made and Dane had pinged me so I double checked and notice key in the tests of core.
https://github.com/formio/formio.js/pull/5526
Key shouldn't be available in repo. 
n/a
Not present in new dev tag from this PR
When using the dev tag `2.0.0-dev.103.ec176d1` no longer see the key appear in packages within formio-server
When searching..
=> FIO-7675: Map Key From Core

src/sdk/Formio.ts, src/sdk/__tests__/Formio.test.ts
https://formio.atlassian.net/browse/FIO-8354
Changed the events emitted by Formio to fallback to passing the response object to emit argument if response.body is undefined. This allows for clients using this api to handle these events based on the data in the response object.
I chose this solution because it allows for backwards compatibility by keeping response.body as a possible argument in the emit function
None
N/A
manually tested
=> FIO-8354: fallback to passing response in argument if response.body is undefined

experimental.d.ts, experimental.js, package.json, src/experimental/base/component/Component.ts, src/experimental/core.ts, src/experimental/index.ts, src/experimental/model/Model.ts, src/experimental/model/NestedArrayModel.ts, src/experimental/model/NestedDataModel.ts, src/experimental/template/Template.ts
https://formio.atlassian.net/browse/FIO-XXXX
*Use this section to provide a summary description of the changes you've made*
*Use this section to justify your choices*
*Use this section to list any dependent changes/PRs in other Form.io modules*
*Use this section to describe how you tested your changes; if you haven't included automated tests, justify your reasoning*
=> Experimental component changes

src/utils/__tests__/formUtil.test.ts, src/utils/conditions.ts, src/utils/formUtil.ts
https://formio.atlassian.net/browse/FIO-8512
- fixed an issue where compPath is not defined correctly inside getComponentActualValue, since layout components are considered for path calculation. Added logic that takes only closest input component for path calculation;
- fixed an issue where wrong component is passed as an argument to getComponentActualValue inside checkSimpleConditional. Before the conditional component was passed together with path of the condition component, I have changed it to pass the condition component (that is on which the visibility of the component depends).
Manually + test added
=> FIO-8512: fixed an issue where conditionally visible data inside layout components inside editGrid/dataGrid is unset on server side

src/process/validation/util.ts
https://formio.atlassian.net/browse/FIO-8450
Custom validation error messages were not populated, this PR adds a fix
*Use this section to justify your choices*
[formio:1759](https://github.com/formio/formio/pull/1759)
Test is added in [formio:1759](https://github.com/formio/formio/pull/1759)
=> FIO-8450: Fix custom error message for unique validation

src/utils/__tests__/date.test.ts, src/utils/date.ts
https://formio.atlassian.net/browse/FIO-8477
This PR addresses issues encountered with the `formatDate` function, originally implemented in the formio.js library, which utilizes the moment-timezone library for timezone formatting. Specifically, the `z` [format option](https://momentjs.com/timezone/docs/#/using-timezones/formatting/) in moment-timezone, used for abbreviated timezone names, does not directly translate to the dayjs library we currently employ. To bridge this functionality gap, the [advancedFormat](https://day.js.org/docs/en/plugin/advanced-format) plugin from dayjs is necessary. However, a known issue with dayjs ([#1154](https://github.com/iamkun/dayjs/issues/1154)) results in the generation of `GMT+..` formats instead of abbreviated timezone names. Notably, the `zzz` format …
=> FIO-8477: Fix the timezones issue in formatDate function

src/process/__tests__/process.test.ts, src/process/filter/index.ts
https://formio.atlassian.net/browse/FIO-8650
The filter logic was skipping array model types, letting the child fields populate the data object.  This wasn't working for empty grids. 
Added a special case for array model types when the data is empty.
*Use this section to list any dependent changes/PRs in other Form.io modules*
*Use this section to describe how you tested your changes; if you haven't included automated tests, justify your reasoning*
=> FIO-8650 -- returning empty array for empty edit grids

src/process/validation/i18n/en.ts, src/process/validation/rules/__tests__/validateRequiredDay.test.ts, src/process/validation/rules/validateRequiredDay.ts
https://formio.atlassian.net/browse/FIO-8645
Added tests and translations for validateRequiredDay validation
automated tests
=> FIO-8645: added tests and translations for validateRequiredDay

src/process/validation/rules/__tests__/validateAvailableItems.test.ts, src/process/validation/rules/validateAvailableItems.ts
https://formio.atlassian.net/browse/FIO-8639
https://formio.atlassian.net/browse/FIO-8685
*Fixed the behavior of the Select component, when it was always checked for available items even if onlyAvailableItems parameter was set to false*
*n/a*
*https://github.com/formio/formio.js/pull/5695*
*automated tests have been added*
=> FIO-8639 fixed validation for select component if onlyAvailableItems is set to false

src/process/__tests__/process.test.ts, src/process/clearHidden.ts, src/process/conditions/index.ts
https://formio.atlassian.net/browse/FIO-8537
The issue was that fields that should have been hidden on the submission were
two things changed:
1. in the `conditionalProcess` function there was a check to see if clearOnHide was checked before setting the conditional fields in the context scope.  This was removed.
2. In the `clearHiddenProcess` function, the path in the conditional scope entries were checking the complete path of the component to determine if the submission data should be removed.  However, the path being set in scope conditional array is a relative path from the parent, and therefore skipped.  The change was to do a partial match on the conditional path to see if it should be omitted.
3. 
*Use this section to describe any potentially breaking changes this …
=> fixing child components being displayed when they should be removed when clearOnHide is set

src/types/Form.ts
https://formio.atlassian.net/browse/FIO-7733
I've changed the Form type to reflect that (at least for now) this type should reflect both "input" forms (e.g. to the renderer itself, which only require a components array) and "output" forms (e.g. from the server, which may contain database metadata along with Form.io Enterprise Server-specific access control data). 
n/a
n/a
n/a
=> FIO-7733: update most form params to optional

src/process/__tests__/process.test.ts, src/utils/logic.ts
https://formio.atlassian.net/browse/FIO-8626
`@formio/vm` relies on conditionally hidden components to render the email correctly. Previously, we tracked only conditionals that come from logic and set the `hidden` property to `true`. However, we also need to handle the opposite operation, where a component is hidden but logic sets the `hidden` property to `false`.
Unit tests
=> FIO-8626: Updated conditionally hidden logic

src/process/__tests__/process.test.ts, src/utils/logic.ts
https://formio.atlassian.net/browse/FIO-8273
*Fixed the behavior when the properties of the original component changed when the logic was triggered, which led to a change in all  nested components  inside the Data components*
*n/a*
*n/a*
*Automated tests have been added. All tests pass locally*
=> FIO-8273 fixed advanced logic for data components

Changelog.md, Readme.md, package.json, src/process/__tests__/fixtures/index.ts, src/process/__tests__/fixtures/skipValidForConditionallyHiddenComp.json, src/process/__tests__/fixtures/skipValidForLogicallyHiddenComp.json, src/process/__tests__/fixtures/skipValidWithHiddenParentComp.json, src/process/__tests__/process.test.ts, src/process/validation/index.ts, src/utils/formUtil.ts, src/utils/isParentHidden.ts
https://formio.atlassian.net/browse/FIO-8731
Fixed some scenarios, when required component, placed in a conditionally/simply hidden parent component, got validated.
*Use this section to justify your choices*
*Use this section to list any dependent changes/PRs in other Form.io modules*
I've added automated tests for different scenarios
=> FIO-8731: Fixes component gets validated when being in a hidden parent

src/process/conditions/index.ts, src/process/hiddenChildren.ts, src/process/hideChildren.ts, src/process/index.ts, src/process/process.ts, src/process/validation/index.ts, src/utils/formUtil.ts, src/utils/logic.ts
https://formio.atlassian.net/browse/FIO-8731
This commit: 
* reverts adding layout component logical branch to eachComponentData
* reverts the isParent check in validation subroutine
* adds a hiddenChildren processor to core that adds hidden properties to children
This is _not the most ideal solution_ for two reasons: 
(a) it continues ad-hoc iteration over the components tree, which has the potential to be a bottleneck in situations where there are many levels of nested hidden components (there is no mechanism to avoid repeating the hiddenChildren processor).  It would better to eliminate this ad-hoc iteration entirely to go with some approach that allowed processors to pass values down to child nested components. (Note that we were already doing this, this PR just codifies it into its …
=> FIO-8731: Update fix to nested hidden components

src/process/__tests__/fixtures/util.ts, src/process/__tests__/process.test.ts, src/process/filter/__tests__/filter.test.ts, src/process/normalize/__tests__/normalize.test.ts, src/utils/formUtil.ts
https://formio.atlassian.net/browse/FIO-8778
The filter process was not accounting for "map" model types, which resemble "object" model types but crucially don't have child components (or at least, child components that get iterated into). This PR updates the getModelType function to account for the "map" model type.
n/a
n/a
Added some automated tests.
=> FIO-8778: add case for map component model type in filter; add tests

src/utils/__tests__/formUtil.test.ts, src/utils/formUtil.ts
https://formio.atlassian.net/browse/FIO-8769
*Fixed behavior when hidden property wasn't work when the conditional is saved in an invalid state. Added check of the Simple Conditions properties and added validation for Conditional tab on EditForm modal window*
*n/a*
*https://github.com/formio/premium/pull/320*
*Automated tests has been added*
=> FIO-8769 added check for the simpleConditional properties state

src/process/validation/rules/__tests__/validateMultiple.test.ts, src/process/validation/rules/validateMultiple.ts
https://formio.atlassian.net/browse/FIO-8848
*Fixed an issue with saving a value for non multiple Text Area componentl if the "Save as" property is set to "json". Previously, if non multiple Text Area with 'Save As'= 'json' was filled in as an array, 'nonarray' Error was displayed. This caused regression when it was not possible to save Select component with Data Source Type Raw JSON. This has been fixed by adding an additional condition for validateMultiple*
*n/a*
*n/a*
*Automated test has been added*
=> FIO-8848 fixed validation for TextArea with Save as Json

src/process/__tests__/process.test.ts, src/utils/formUtil.ts
https://formio.atlassian.net/browse/FIO-8810
Sometimes the submission, that we pass to validator, does not have reference data for nested forms. The value of such nested forms looks like this { id: 'someID', data: {} }.  I found at least 2 cases when it happens for PUT requests:
1) when we want to change the submission of wizard form that have at least 1 page in the middle of the wizard with deeply nested forms. In this case the user can open 1st page and make changes, then go to the last page to submit the form. The middle page with deeply nested forms is not opened, it means that the nested form submission data is not loaded (it is lazy loaded from level 3). So, the server gets the empty data (just with reference ID) for such nested form.
2) when we submit the webform …
=> FIO-8810: fixed an issue where user unables to resubmit (change) the form with several levels of nested forms with required fields

src/process/validation/rules/__tests__/validateDay.test.ts, src/process/validation/rules/validateDay.ts
https://formio.atlassian.net/browse/FIO-8798
Day component validation was changed.
The changes were caused by a change in the formation of the data string for the Day component with hidden fields.
if a element of the day component is hidden, it should be excluded from the string instead of populating with ‘00’ 
Examples (new years):  
day / year == ‘01/2024’ 
month / year =  ‘01/2024’ 
day / month  = ‘01/01’
autotests
=> FIO-8798: updated day component validation

src/process/clearHidden.ts, src/process/conditions/__tests__/conditions.test.ts, src/process/conditions/index.ts, src/process/hideChildren.ts
https://formio.atlassian.net/browse/FIO-8886
Previously, we compared conditional component paths to the context path using `Array.prototype.includes`, which would trigger a false positive when the string path of the component was "contained" within another key (e.g. a key "or" would be found in another hidden key "information"). Since we should be adding components to the conditionals scope keyed by absolute paths, this PR changes the comparison to strict equality.
n/a
n/a
The main concern here is ensuring that components added to the conditional scope are keyed by absolute data path, so I wrote tests trying to ensure that even deeply nested components get added to that scope using an absolute path. Additionally, formio and formio-server tests pass with this change.
=> FIO-8885 & FIO-8886: use strict equality check for conditional component paths rather than Array.prototype.includes

src/experimental/base/array/__tests__/ArrayComponent.test.ts, src/experimental/model/NestedArrayModel.ts
https://formio.atlassian.net/browse/FIO-8901
**Issue:** When setting a nested array model's `dataValue` to a smaller size than it was previously, the new `dataValue` contains more items than it should. This happens because when we remove excessive items by iterating over the array from the beginning, each removal causes the subsequent elements to shift left, leading to skipped elements during iteration.
**Solution:** Iterate over the array in reverse order to avoid skipping elements when removing items.
Updated the existing test case.
=> FIO-8901: Fixed incorrect handling of excessive rows in nested array model

src/process/validation/rules/validateMultiple.ts, src/types/BaseComponent.ts, src/utils/__tests__/formUtil.test.ts, src/utils/date.ts, src/utils/formUtil.ts
https://formio.atlassian.net/browse/FIO-8912
Some [work](https://github.com/formio/formio.js/pull/5777) was [done](https://github.com/formio/formio.js/pull/5798) to consolidate normalization of components with `multiple: true`. However, this doesn't account for things like hidden components or custom components, which can contain "array"-like data models that previously would get validated as `multiple.` This PR changes the core library's model type evaluation to (a) default to an opt-in model type in the component JSON, and (b) fallback to known component model types.
n/a
n/a
Added some automated testing around `getModelType`.
=> FIO-8912: update validateMultiple to account for model types

src/process/filter/__tests__/filter.test.ts, src/process/filter/index.ts, src/process/populate/index.ts, src/process/validation/rules/validateMultiple.ts, src/utils/formUtil.ts
https://formio.atlassian.net/browse/FIO-8912
Minor changes to model types, naming: `nestedArray` now reflects components that store their values as an array _and_ have nested components.
n/a
n/a
formiojs, formio and formio-server tests pass
=> FIO-8912: updates to model types, naming

src/process/validation/rules/__tests__/validateDay.test.ts, src/process/validation/rules/validateDay.ts
https://formio.atlassian.net/browse/FIO-8986
*Fixed Validation of the Day component with PartialDay and two hidden fields (ex. hidden day and year, hidden month and year or hidden month and day)*
*n/a*
*n/a*
*Automated tests have been added, all tests pass locally*
=> FIO-8986 fixed validation for Day component with two hidden fields

src/process/__tests__/process.test.ts, src/utils/formUtil.ts
https://formio.atlassian.net/browse/FIO-9055
Previously, nested data components (e.g. edit grid, container, data grid, etc.) did not handle the case of a conditional component that was _outside_ of the component's contextual row value. In other words, an edit grid component that contains a child text field that itself contains a conditional based on a parent-level component:
```
const form = {
display: 'form',
components: [
{
label: 'Select',
widget: 'choicesjs',
tableView: true,
data: {
values: [
{
label: 'Action1',
value: 'action1',
},
{
label: 'Custom',
value: 'custom',
},
],
},
key: 'select',
type: 'select',
input: true,
},
{
label: 'Edit Grid',
tableView: false,
rowDrafts: false,
key: 'editGrid',
type: 'editgrid',
displayAsTable: false,
input: true,
components: [
{
label: 'Text …
```
=> FIO-9055: separate rowPath from componentPath in getComponentActualValue fn

src/process/filter/__tests__/filter.test.ts, src/process/filter/index.ts, src/process/validation/rules/validateMultiple.ts, src/utils/formUtil.ts
https://formio.atlassian.net/browse/FIO-9033
Previously, Tagpad was assigned to the 'nestedArray' data model that implies that each object inside component's value array will consist of nested components keys. Which is not correct in Tagpad's case, because its value structure is 
[
{
coordinates: { x, y },
data: {},
},
]
where 'data' is an actual property containing all the nested components' values. 
Because of that during the filter process, Tagpad's value was assigned to an empty array and was never refilled with nested component's values. 
New data type called 'nestedDataArray' was provided for such scenarios where it looks for the nested component's values inside 'data' property of each object in the array and does not clear any property outside of the 'data' one 
*Use this section …
=> FIO-9033 tagpad data is not saved

src/process/__tests__/process.test.ts, src/process/validation/rules/validateMultiple.ts, src/utils/__tests__/formUtil.test.ts, src/utils/formUtil.ts
https://formio.atlassian.net/browse/FIO-9059
Added a check that returns any type for textarea that is configured to save as JSON
https://github.com/formio/formio.js/pull/5829
tests
=> FIO-9059: fixed an issue where  the string type returns for textarea with json type

src/process/clearHidden.ts, src/process/conditions/index.ts, src/process/hideChildren.ts, src/process/processOne.ts, src/process/validation/index.ts, src/process/validation/rules/validateRequired.ts, src/types/BaseComponent.ts, src/utils/formUtil/eachComponentData.ts, src/utils/formUtil/eachComponentDataAsync.ts, src/utils/logic.ts, src/utils/utils.ts
https://formio.atlassian.net/browse/FIO-9002
Fixed a spelling error and fixed minor lints
n/a
n/a
n/a
=> FIO-9002: fix spelling error and minor linting

src/process/__tests__/process.test.ts
https://formio.atlassian.net/browse/FIO-9202
The issue FIO-9202 is not reproducible in master as it was fixed by https://github.com/formio/core/pull/141. Just added a test.  Made a separate PR for 3.2.x for a fix.
https://github.com/formio/core/pull/166
=> FIO-9202: added a test for the issue with conditional components inside wizard

src/process/validation/__tests__/Validator.test.ts, src/process/validation/__tests__/fixtures/forms.ts, src/process/validation/rules/__tests__/validateTime.test.ts, src/process/validation/rules/validateTime.ts
https://formio.atlassian.net/browse/FIO-9086
Time component validation was changed as follows:
Server side and client side evaluations of validity use component dataFormat for validation.
For correct use on client side wad added changes on formio.js ( only this.dataValue is used for validation)
Those changes help avoid validation errors caused by mismatches between data display and storage format.
https://github.com/formio/formio.js/pull/5834
manually,
autotests
*Use this section to describe how you tested your changes; if you haven't included automated tests, justify your reasoning*
=> FIO-9086: use for validation only dataFormat (data storage format)

src/process/__tests__/process.test.ts, src/utils/formUtil/index.ts, src/utils/operators/IsEqualTo.js, src/utils/operators/IsNotEqualTo.js
https://formio.atlassian.net/browse/FIO-9189
- added a special check for the select resource with object type in isEqualTo operator
- changed isNotEqualTo operator to use comparison logic from  isEqualTo operator
- moved some method from formiojs to core
tests + manually
=> FIO-9189: fixed an issue where data is lost after submission for the conditionally visible field when the condition is based on select resource

src/process/validation/rules/__tests__/validateAvailableItems.test.ts, src/process/validation/rules/validateAvailableItems.ts
https://formio.atlassian.net/browse/FIO-9244
Changed incorrect values for Radio Component.
n/a
n/a
tested manually, fixed incorrect values in existing test from https://github.com/formio/core/pull/152
=> FIO-9244: fixed an issue where Radio component with Allow only available values checked does not submit

src/process/validation/rules/__tests__/validateValueProperty.test.ts, src/process/validation/rules/validateValueProperty.ts, src/types/PassedComponentInstance.ts
https://formio.atlassian.net/browse/FIO-9280
*Since the Radio component and the Select component support various data types, including objects and boolean values, validation of the value property is triggered only for the Select Boxes component. Also, validation is triggered only in the form builder. If the value for the SelectBoxes component is invalid, an error is displayed that does not allow saving the component with invalid values.*
n/a
*https://github.com/formio/formio.js/pull/5894*
locally, automated tests have been added
=> FIO-9280 updated validation of value property

src/process/validation/rules/__tests__/validateRequiredDay.test.ts, src/process/validation/rules/validateRequiredDay.ts
https://formio.atlassian.net/browse/FIO-9344
*Fixed require validation for Day component when Day component includes hidden fields*
*n/a*
*n/a*
Automated tests have been added. All tests pass locally
=> FIO-9344 fixed require validation for day component

src/process/__tests__/process.test.ts, src/utils/formUtil/eachComponentData.ts, src/utils/formUtil/eachComponentDataAsync.ts
https://formio.atlassian.net/browse/FIO-9266
https://formio.atlassian.net/browse/FIO-9267
https://formio.atlassian.net/browse/FIO-9268
Previously, we were skipping processing any Nested Form's child components if there were no data provided for it (if the empty object was provided, it woould not skip though). That was causing an issue with submissions made through API that do not indlude data for the neste form, but must be still validated (because some fields of the child form are required, for example).
After discussion on the dev support we decide that the aussumptions that we can skip processing of nested form's child components if it has no data was wrong and we have to change it.
There are still some cases when we want to skip it: when the nested form's submission is saved as …
=> FIO-9266,FIO-9267,FIO-9268: Fixes an issue where nested forms will be not validated if there are no data provided

src/process/validation/index.ts, src/process/validation/rules/validateRequired.ts
https://formio.atlassian.net/browse/FIO-9329
Changes to when we validate based on visibility, namely that the `shouldSkipValidation` function checks for the `validateWhenHidden` flag AND general visibility (so both conditionally hidden components and intentionally hidden ones).
n/a
n/a
Tests here are passing, automated tests were included in @formio/js
=> FIO-9329: fix issue where validateWhenHidden now validates hidden and conditionally hidden components

src/process/validation/rules/validateCustom.ts
https://formio.atlassian.net/browse/FIO-8640
The rowIndex in evelContext of custom validation was always overridden by context.index that is getting assigned only in a single place (when we have component set to multiple and process all its values at once instead of one by one) 
_Use this section to describe any potentially breaking changes this PR introduces or any effects this PR might have on backwards compatibility_
_Use this section to describe how you tested your changes; if you haven't included automated tests, justify your reasoning_
=> FIO-8640: Fixes an issue where rowIndex is undefined in custom validation

src/process/validation/rules/__tests__/validateAvailableItems.test.ts, src/process/validation/rules/validateAvailableItems.ts
https://formio.atlassian.net/browse/FIO-9321
*The problem of incorrect Only Available Items validation of the Select Boxes component value has been fixed.*
*The value of the Select boxes component is a map with pairs key (value option) - value (true or false). Therefore the check for the difference between the data value keys and allowed options values has been added.*
*n/a*
*n/a*
*Automated tests have been added. All tests pass locally*
=> FIO-9321 fixed onlyAlailableItems validation for select Boxes

src/process/__tests__/process.test.ts, src/process/calculation/index.ts, src/process/fetch/index.ts
https://formio.atlassian.net/browse/FIO-9357
*Previously, the calculation of values on the server side based on the DataSource component did not work correctly, because after fetching data for the dataSource, the data was not saved, and the fetched value included only the Boolean value. Therefore, during the calculation process based on the value of data.dataSource, data.dataSource is undefined. This behavior has been fixed by adding fetched data when calculating process*
*n/a*
*n/a*
*Automated test has been added . All tests pass locally*
=> FIO-9357 fixed calculation based on DataSource component

src/utils/formUtil/index.ts
https://formio.atlassian.net/browse/FIO-9266
Removed the lines that skip proccessing nested forms if there are no data provided and were removed earlier as part of my fix, but then were accidentially returned back while merging conflicts in the other PR.  
_Use this section to describe any potentially breaking changes this PR introduces or any effects this PR might have on backwards compatibility_
_Use this section to describe how you tested your changes; if you haven't included automated tests, justify your reasoning_
=> FIO-9266/FIO-9267/FIO-9268: Fixes an issue where nested form validation will be skipped if parent form submits empty data

src/process/__tests__/process.test.ts, src/process/conditions/index.ts
https://formio.atlassian.net/browse/FIO-9465
Fixed path generation (for scope.conditionals) during conditional processing.
The changes allow avoiding the clearing of req.data for situations when wizard form have panels with specified conditionals relying on a component within the form. Unnecessary data clearing couses problems in the validation process of nested forms.
autotests
manually
=> FIO-9465: fix conditionals path for panel component

src/process/calculation/index.ts, src/utils/formUtil/__tests__/eachComponentData.test.ts, src/utils/formUtil/eachComponentData.ts, src/utils/formUtil/eachComponentDataAsync.ts, src/utils/formUtil/index.ts
https://formio.atlassian.net/browse/FIO-9508
We [added an `includeAll` flag to the `eachComponentData` family of functions](https://github.com/formio/core/pull/84) to ensure that even when there is no submission data associated with a component you could opt in to iterating over it. However, this was not taking into account components nested in an e.g. data grid. This PR fixes that issue, commits a small formatting change, and adds an unrelated utility function for use in our other libraries.
n/a
n/a
Automated / manual testing
=> FIO-9508: includeAll flag now works with nested components

src/process/normalize/__tests__/normalize.test.ts, src/process/normalize/index.ts
https://formio.atlassian.net/browse/FIO-8119
Deleted tags from data if the value is null
So that 9.x behaves similarly to 8.x
N/A
N/A
Added automated test
=> FIO-8119: remove tags from data if value is null

src/error/FieldError.ts, src/process/__tests__/process.test.ts
https://formio.atlassian.net/browse/FIO-9668
I've added "level" field to be assigned to custom errors, since it's needed in formio.js, as it filters out all non-"error" level messages.
Our other errors (required, min, max, etc.) already have that "level" assigned and work fine.
_Use this section to describe any potentially breaking changes this PR introduces or any effects this PR might have on backwards compatibility_
I've added an automated test case.
=> FIO-9668: Fix custom error messages are not highlighted

package.json, src/sdk/Formio.ts
https://formio.atlassian.net/browse/FIO-9642
Included response information in the error
Tech debt: changed prepublish -> prepublishOnly
Allows for better error handling by customers. Sometimes they want to handle errors based on status codes, urls, etc. Adding the response body allows them to do this
The error will no longer just be text or json. It will now be an object and the error that was returned previously will now be in a property called error in the object
N/A
Manually tested
=> FIO-9642: enhance error information

src/process/__tests__/process.test.ts, src/process/conditions/index.ts
https://formio.atlassian.net/browse/FIO-9796
There is an issue where if you have simple conditionals dependent on a calculated value state, the state of "conditionallyHidden" gets set and never gets updated with the correct state. This change ensures that the state is always re-calculated when the processors are re-evaluated.
None
None
Automated tests written
=> FIO-9796: Fixed issue where the conditions from a previous run may be in the wrong state for conditionally hidden.

src/process/validation/rules/__tests__/fixtures/components.ts, src/process/validation/rules/__tests__/validateRequired.test.ts, src/process/validation/rules/validateRequired.ts
https://formio.atlassian.net/browse/FIO-9776
**Issue**: Every value in the object of the manual mode of the address component should have a value to pass the required validation.
**Solution**: Added a filter to exclude the Address2 field from the required validation.
Unit testing.
=> FIO-9776: Excluded Address2 field from required validation

src/utils/unwind.ts
https://formio.atlassian.net/browse/FIO-9737
Adds the deprecated tag to the `unwind` utility method. See [pdf-server#428](https://github.com/formio/pdf-server/pull/428) for details.
n/a
n/a
n/a
=> FIO-9737: add deprecated tag to the unwind method

src/modules/jsonlogic/index.ts
n/a
The exported evaluator was not "extendable," meaning it did have a `registerEvaluator` method. This PR updates the export.
n/a
n/a
n/a
=> update exported evaluator to be 'extendable' version

src/process/process.ts
https://formio.atlassian.net/browse/FIO-9874
The issue were caused by using wrong instance. Disappearing operands are nested inside columns component that has `modelType = 'none'`, having two columns component within the form caused path collision. Added condition to use fullpath (that is unique) to set the exact instance.
n/a
n/a
tested manually, all existing tests pass locally
=> FIO-9874: fixed an issue where operands disappear

src/utils/__tests__/formUtil.test.ts, src/utils/formUtil/index.ts
https://formio.atlassian.net/browse/FIO-9964
When the form has several components with the same key (e.g. components with paths 'repeatedKey' and 'container.repeatedKey'), and you try to get the component using the key 'repeatedKey', the getComponent always returns the component with this key that goes the last in the eachComponent iteration, that is the component with path 'container.repeatedKey'. So, there is no way to get the 'repeatedKey'  component. This PR made it so that getComponent returns the component that matches first within the eachComponent iteration. If someone needs to get the 'container.repeatedKey' component, instead of the key, the path should be passed to getComponent.
This fix is for 2.3.x only.
The getComponent in formio/js@4.x works fine because …
=> 2.3.x: FIO-9964: fixed an issue where getComponent returns wrong component when the form includes several components with the same key

src/utils/Evaluator.ts, src/utils/__tests__/Evaluator.test.ts
https://formio.atlassian.net/browse/FIO-9942
Refactored the static noeval flag across BaseEvaluator, Evaluator, and JSONLogicEvaluator classes to ensure consistency. Introduced a getter and setter for noeval in BaseEvaluator to centralize its value and make it shared across all evaluator layers. 
Previously, each evaluator class had its own separate static noeval property, which caused inconsistencies when toggling evaluation behavior. 
-
-
manually
autotests
=> FIO-9942: Fix issue with disabling evaluations

src/server/actions/save/save.js
https://formio.atlassian.net/browse/FIO-8544
The code has been refactored to use async/await syntax, replacing the async library dependency. 
-
-
autotests
=> FIO-8544: Replace async callbacks with async/await

src/utils/Evaluator.ts
https://formio.atlassian.net/browse/FIO-9942
Added a static registerEvaluator method to work properly with extended evaluator classes by using this instead of referencing the base Evaluator class directly.
This ensures that any subclass extending the Evaluator can successfully register additional methods or properties using registerEvaluator.
-
manually  during the process of connecting @formio/protected-eval to 5.x renderer.
=> FIO-9942: use 'this' instead of 'Evaluator' for inheritance support

src/utils/formUtil/eachComponentData.ts, src/utils/formUtil/eachComponentDataAsync.ts
https://formio.atlassian.net/browse/FIO-9885
If  we had a two layout components that have conditions to show and one of them is hidden and the other is shown and Nested Component that is conditionally shown, the layout components that is hidden was processed with a dataPath that does not contain a component's key if it is a layout component which was causing clearing the Nested Form's data.  
_Use this section to describe how you tested your changes; if you haven't included automated tests, justify your reasoning_
=> FIO-9885: Fixes an issue where conditionally hidden layout components could cause data loss of the conditionally hidden Nested Form

Changelog.md, package.json, src/process/__tests__/process.test.ts, src/types/project/Project.ts, src/utils/formUtil/index.ts
https://formio.atlassian.net/browse/FIO-10124
When making the pathing changes, we added a conditional that essentially said "don't add the component's key to the path if it has a model type of 'none' (so, layout components) OR a model type of 'content' (so, content and HTML components)." However, I think this was an oversight - there is no reason that I can see to omit the component keys from components with a content model type, because they are still subject to things like conditionals and need to have data paths that are accessible to processors. Indeed, the cause of this bug was that when such components were nested in containers, their "path" (or data path) defaulted to their parent container, which would cause the `clearHidden` processor to clear data at the incorrect path.
n/a
n/a …
=> FIO-10124: fixes an issue where HTML and Content components are clearing sibling components when nested in a container

src/process/__tests__/fixtures/componentsWithDefaultValues.json, src/process/__tests__/fixtures/index.ts, src/process/__tests__/process.test.ts, src/process/filter/index.ts
https://formio.atlassian.net/browse/FIO-9984
Previously, our filtering process ignored default values that are set by the defaultValue processors in the data object.
This PR fixes it.
Manually + tests
=> FIO-9984: fixed an issue where default value is not set when the component does not have value in submission

src/sdk/Formio.ts
https://formio.atlassian.net/browse/FIO-10209
#224 introduced a breaking change that changed the shape of the error returned by the core SDK fetch subroutine. This was too aggressive because there is a lot of legacy code that consumes those errors (e.g. in the Developer Portal application, a toast is displayed). 
n/a
n/a
n/a
=> FIO-10209: fix issue with incorrect error handling in developer portal app

src/utils/formUtil/index.ts
https://formio.atlassian.net/browse/FIO-10215
We made a change to "normalize" the context value passed into the evaluate sandbox. It needs "scope" and "options" to function correctly.
n/a
n/a
n/a
=> FIO-10215: add options, scope to normalized context

src/process/validation/rules/validateCustom.ts
https://formio.atlassian.net/browse/FIO-10263
When we validate on the renderer, we [don't provide a submission value into the context](). This is a problem, because evaluation contexts need the submission variable as part of the stuff we provide the form user. However, when I made updates to the Evaluator, I accidentally added a submission "overwrite" to the evaluation context instead of just relying on what we get from the instance itself. This PR fixes the error.
n/a
n/a
Tests for this really belong in formio.js - I will add some and link them here.
=> FIO-10263: rely on instance level evaluation context to provide us with submission variable

src/process/defaultValue/index.ts, src/process/filter/index.ts
https://formio.atlassian.net/browse/FIO-9984
Moved logic that does not allow to set false default values from filter processor to default value processor 
with  8x
tests
=> FIO-9984: do not set false default values on server as it is in 8x server

src/process/__tests__/process.test.ts, src/process/calculation/index.ts, src/process/clearHidden/index.ts, src/process/conditions/index.ts, src/process/defaultValue/index.ts, src/process/fetch/index.ts, src/process/filter/__tests__/filter.test.ts, src/process/filter/index.ts, src/process/index.ts, src/process/normalize/index.ts, src/process/process.ts, src/process/processOne.ts, src/process/validation/index.ts, src/types/formUtil.ts, src/types/process/ProcessorFn.ts, src/types/process/ProcessorInfo.ts, src/types/process/calculation/CalculationScope.ts, src/types/process/defaultValue/DefaultValueScope.ts, src/types/process/fetch/FetchScope.ts, src/types/process/filter/FilterScope.ts, src/types/process/logic/LogicScope.ts, src/utils/formUtil/eachComponentData.ts, src/utils/formUtil/eachComponentDataAsync.ts, src/utils/formUtil/index.ts, src/utils/logic.ts
https://formio.atlassian.net/browse/FIO-10337
Before this change, the data processing was broken up into two separate "process" loops. The reason for this was to separate the processors that run within a VM vs. the processors that run outside of a vm. The initial thought was that this would improve performance by only executing the processors that need to be executed in a VM in a separate minified process.  An issue shows up, however, when you have a very large form (1000+ fields) since this requires that all of these fields be iterated over twice vs. one single loop.
This change mitigates that problem by reverting back to a single loop strategy for performing the processing. Also, since we only have a single loop being executed, much of the changes were to the "post" processors that …
=> FIO-10337: Refactored the core data processors to significantly improve performance

src/process/process.ts, src/process/processOne.ts, src/utils/formUtil/eachComponentData.ts, src/utils/formUtil/eachComponentDataAsync.ts
https://formio.atlassian.net/browse/FIO-10408
There is an issue where the iteration through nested components was being blocked if the row for that component is undefined. This is a problem, especially if there are "required" fields that need that data and the data is not getting validated correctly. The only case where this is not the case is if the component is a nested array (datagrid and editgrid) where we should be skipping the processing of the children since this is not needed for nested arrays that are empty.
Yes
None
Manual, and ran existing automated tests.
=> FIO-10408: Fixed issues with the nested field validations.

src/process/__tests__/process.test.ts, src/process/calculation/index.ts, src/process/clearHidden/index.ts, src/process/conditions/index.ts, src/process/defaultValue/index.ts, src/process/fetch/index.ts, src/process/filter/__tests__/filter.test.ts, src/process/filter/index.ts, src/process/index.ts, src/process/normalize/index.ts, src/process/process.ts, src/process/processOne.ts, src/process/validation/index.ts, src/types/formUtil.ts, src/types/process/ProcessorFn.ts, src/types/process/ProcessorInfo.ts, src/types/process/calculation/CalculationScope.ts, src/types/process/defaultValue/DefaultValueScope.ts, src/types/process/fetch/FetchScope.ts, src/types/process/filter/FilterScope.ts, src/types/process/logic/LogicScope.ts, src/utils/formUtil/eachComponentData.ts, src/utils/formUtil/eachComponentDataAsync.ts, src/utils/formUtil/index.ts, src/utils/logic.ts
https://formio.atlassian.net/browse/FIO-10337
https://formio.atlassian.net/browse/FIO-10028
This merges the following PR's into the 2.5.x branch of core.
- https://github.com/formio/core/pull/270
- https://github.com/formio/core/pull/275
None
None
Manual + Automated
=> FIO-10337, FIO-10028: Added performance and data processing improvements for the 2.5.x branch

src/process/validation/rules/validateCustom.ts, src/utils/__tests__/Evaluator.test.ts, src/utils/conditions.ts
https://formio.atlassian.net/browse/FIO-10554
If you have a calculation where you do not actually set the variable, then unexpected things occur.
For example:
```
if (someCondition) {
show = false;
}
```
This would historically show the field since it historically would be true by default, but now it hides because the "show" variable is undefined and then returns the wrong value.
This resolves a breaking change between 9.x and 8.x deployments for server side behavior.
None
=> FIO-10554: Fixed issue where if you do not set the variable in a calculation, that unexpected behavior occurs.

src/process/__tests__/process.test.ts, src/types/process/logic/LogicContext.ts, src/utils/logic.ts
https://formio.atlassian.net/browse/FIO-10588
This is PR https://github.com/formio/formio-monorepo/pull/418 adopted for 2.3.0-patch:
_Use this section to justify your choices_
_Use this section to describe any potentially breaking changes this PR introduces or any effects this PR might have on backwards compatibility_
_Use this section to describe how you tested your changes; if you haven't included automated tests, justify your reasoning_
=> 2.3.0-patch: FIO-10588: fixed an issue where logic with the result variable does not work properly on server side
